// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingClient.Models
{
   
    public  class branch
    {
       
        [Key]
        [Required]
        [DisplayName("Branch ID")]
        public int branch_id { get; set; }
        [Required]
        [DisplayName("Branch Name")]
        [StringLength(50)]
        public string branch_name { get; set; }
        [Required]
        [DisplayName("Branch City")]
        [StringLength(50)]
        public string branch_city { get; set; }
        [Required]
        [DisplayName("Branch Country")]
        [StringLength(50)]
        public string branch_country { get; set; }
       
    }
}