// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingClient.Models
{
    public  class resident_room
    {
        [Required]
        [Key]
        [DisplayName("Reservation ID")]
        public int reservation_ID { get; set; }
        [Required]
        [DisplayName("Resident nationalID")]
        public long resident_nationalID { get; set; }
        [Required]
        [DisplayName("Room ID")]
        public int room_id { get; set; }
        [Required]
        [DisplayName("Start Date")]
        public DateTime start_book_date { get; set; }
        [Required]
        [DisplayName("End Date")]
        public DateTime end_book_date { get; set; }
        [Required]
        [DisplayName("Checkout Date")]
        public DateTime checkout_date { get; set; }
        [Required]
        [DisplayName("Total price")]
        public decimal room_total_price { get; set; }
        [Required]
        [DisplayName("Canceled")]
        public bool? canceled { get; set; } = false;
        [Required]
        [DisplayName("Active")]
        public bool? is_active { get; set; } = false;

    }
}