// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using HotelBookingClient.Custom_validation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingClient.Models
{
   
    public  class resident
    {
        [Display(Name = "Resident nationalID")]
        [Remote("CheckResidentID", "Resident", ErrorMessage = "Resident ID is already in use")]
        //[NationalIDValidation(ErrorMessage ="National ID must be 14 digit long")]
        public long nationalID { get; set; }
        [StringLength(50)]
        [Display(Name = "Resident Name")]
        [Required(ErrorMessage = "Resident Name is required")]
        public string resident_name { get; set; }
      
    }
}