// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingClient.Models
{
    
    public class user
    {       
        [Key]
        [Required]
        [Display(Name="User ID")]
        public int user_id { get; set; }
        [Required]
        //disabled it for now, id conflicts with login form
        //[Remote(action: "VerifyUserName", controller: "User", ErrorMessage = "Username already exists")]
        [Display(Name = "UserName")]
        public string userName { get; set; }
        [Required]        
        [Display(Name = "User Password")]
        public string userPassword { get; set; }
        [Required]
        [Display(Name = "User Role")]
        public string role { get; set; }
    }
}