// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingDAL.Models
{
    [Table("resident")]
    public partial class resident
    {
        public resident()
        {
            resident_rooms = new HashSet<resident_room>();
        }

        [Key]
        public long nationalID { get; set; }
        [StringLength(50)]
        public string resident_name { get; set; }
        [JsonIgnore]
        [InverseProperty("resident")]
        public virtual ICollection<resident_room> resident_rooms { get; set; }
    }
}