// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingDAL.Models
{
    [Table("room")]
    public partial class room
    {
        public room()
        {
            resident_rooms = new HashSet<resident_room>();
        }

        [Key]
        public int room_id { get; set; }
        public int? room_capacity { get; set; }
        [StringLength(50)]
        public string room_status { get; set; }
        [StringLength(50)]
        public string room_type { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? room_price { get; set; }
        public int? room_number { get; set; }
        public int? branch_id { get; set; }
        public int? room_residents_count { get; set; }
        [JsonIgnore]
        [ForeignKey("branch_id")]
        [InverseProperty("rooms")]
        public virtual branch branch { get; set; }
        [JsonIgnore]
        [InverseProperty("room")]
        public virtual ICollection<resident_room> resident_rooms { get; set; }
    }
}