// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelBookingDAL.Models
{
    [Table("user")]
    public partial class user
    {
        [Key]
        public int user_id { get; set; }
        [StringLength(50)]
        public string userName { get; set; }
        [StringLength(50)]
        public string userPassword { get; set; }
        [StringLength(50)]
        public string role { get; set; }
    }
}